name: Run All Tests (API + UI)

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: seleniarm/standalone-chromium
        ports:
          - 4444:4444

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run all tests
      run: |
        pytest -v

